/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/account/support" |
  "/pages/auth/login" |
  "/pages/auth/register" |
  "/pages/help/index" |
  "/pages/me/me" |
  "/pages/me/profile" |
  "/pages/notifications/index" |
  "/pages/order-complaint/index" |
  "/pages/order-detail/index" |
  "/pages/order-review/index" |
  "/pages/petpal/aftersales" |
  "/pages/petpal/caregiver-earnings" |
  "/pages/petpal/payment-result" |
  "/pages/petpal/refund-result" |
  "/pages/petpal/checkout" |
  "/pages/petpal/caregiver-home" |
  "/pages/petpal/caregiver-orders" |
  "/pages/petpal/caregiver-profile" |
  "/pages/petpal/caregiver-services" |
  "/pages/petpal/getting-started" |
  "/pages/petpal/index" |
  "/pages/petpal/messages" |
  "/pages/petpal/orders" |
  "/pages/petpal/owner-home" |
  "/pages/petpal/pets" |
  "/pages/petpal/reminders" |
  "/pages/petpal/request" |
  "/pages/petpal/request-detail" |
  "/pages/petpal/workbench" |
  "/pages/settings/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/me/me"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
